### PR TITLE
GH-1268 Fix mosaic layout for daily rollup

### LINKED ISSUE #1268: mosaic layout is within a scroll pane
in candidate-2.1

### PR DESCRIPTION
**Pull request by evdhoudt**
Closes #1268

### CODE REVIEW

File: client/src/pages/rollup/Show.js [hunk 1]
```diff
@@ -353,8 +353,8 @@ class BaseRollupShow extends Page {
 	}
 
 	render() {
-		const flexStyle = {display: 'flex', flexDirection: 'column', flex: '1 1 auto'}
-		const mosaicLayoutStyle = { display: 'flex', flex: '1 1 auto' }
+		const flexStyle = { display: 'flex', flexDirection: 'column', flex: '1 1 auto', height: '100%' }
+		const mosaicLayoutStyle = { display: 'flex', flex: '1 1 auto', height: '100%' }
```
Comment (gjvoosten) [inline client/src/pages/rollup/Show.js]: Please make the same two changes in `client/src/pages/insights/Show.js` as well.

**Comment by gjvoosten** [comment]
> Not fully working for me. For instance:
> 
>     * Browser is maximized. I load rollup - layout looks good. I switch to full screen (F11). A scroll bar appears even if there is more realestate. I exit full screen mode - scroll bar remains
> 
>     * Browser is maximized. I load rollup - layout looks good. I resize the browser. Scroll bar appears. I maximize again and it remains.

@vassil Which browser/OS? It's working correctly for me…
