### PR TITLE
Fix Advanced Search and Advanced Select issues

### LINKED ISSUE #1810: Epic 1964: Not enough real estate to display pagination on filtered search / organization partially displayed
1. Select the "Reports" tab on a filtered search
2. Select the "Attendee" filter
3. Type in a name that will display more than six people; there is not enough space for the pagination to be displayed at the bottom of the pop-up list

Principal names are long, position names are long and location names are long.  For example, a position name is six lines.  This creates a long, narrow pop-list.  This also results in the values in the "Organization" column being partially displayed.

### PR DESCRIPTION
**Pull request by evdhoudt**
Both advanced search and advanced select have been updated.
* Check that in the advanced search it is possible to add all the filters and still be able to scroll down.
* Make sure an advanced select widget is at the bottom of the search filter list, and check that the popover also is completely viewable
* Go to create report and check that the advanced select widgets like attendees are also still working correctly

Fixes #1810

### CODE REVIEW

File: client/src/components/AdvancedSearch.js [hunk 1]
```diff
@@ -13,16 +13,23 @@ import {
...
 
+import {
+  Classes,
+  Menu,
+  MenuItem,
+  Popover,
+  Position as PopoverPosition,
+  PopoverInteractionKind
+} from "@blueprintjs/core"
+
```
Comment (gjvoosten) [inline client/src/components/AdvancedSearch.js]: Please honour the correct ordering of imports, and add no blank lines between imports.

File: client/src/components/SearchBar.js [hunk 2]
```diff
@@ -3,19 +3,56 @@ import AdvancedSearch from "components/AdvancedSearch"
...
-  Overlay,
-  Popover
-} from "react-bootstrap"
+import React, { useEffect, useRef, useState, PureComponent } from "react"
+import { Button, Form, FormControl, InputGroup } from "react-bootstrap"
 import { connect } from "react-redux"
 import { useHistory } from "react-router-dom"
 import SEARCH_ICON from "resources/search-alt.png"
 
+import { Popover, Position, PopoverInteractionKind } from "@blueprintjs/core"
```
Comment (gjvoosten) [inline client/src/components/SearchBar.js]: Please honour the correct ordering of imports, and add no blank lines between imports.

File: client/src/components/advancedSelectWidget/AdvancedSelect.js [hunk 3]
```diff
@@ -1,25 +1,22 @@
...
 import PropTypes from "prop-types"
 import React, { Component } from "react"
-import { Button, Col, Overlay, Popover, Row } from "react-bootstrap"
-import ContainerDimensions from "react-container-dimensions"
-import "./AdvancedMultiSelect.css"
+import { Button, Col, FormControl, InputGroup, Row } from "react-bootstrap"
+import { Popover, PopoverInteractionKind, Position } from "@blueprintjs/core"
 
-const MOBILE_WIDTH = 733
+import "./AdvancedSelect.css"
```
Comment (gjvoosten) [inline client/src/components/advancedSelectWidget/AdvancedSelect.js]: Please honour the correct ordering of imports, and add no blank lines between imports.

File: client/src/components/advancedSelectWidget/AdvancedSelect.js [hunk 4]
```diff
@@ -313,11 +289,9 @@ export default class AdvancedSelect extends Component {
     })
   }
 
+  handleInteraction = showOverlay => this.setState({ showOverlay })
+
   handleHideOverlay = () => {
-    if (this.state.inputFocused) {
```
Comment (maradragan) [inline client/src/components/advancedSelectWidget/AdvancedSelect.js]: Probably because of this change the following happens:
- I click on the attendees input field
- the overlay opens
- I select an attendee
- I click on the input field again in order to add a text filter
- but I can't because the overlay closes now

File: client/src/components/AdvancedSearch.js [hunk 5]
```diff
@@ -211,8 +245,6 @@ const AdvancedSearch = props => {
         pathname: "/search"
       })
     }
-    event.preventDefault()
-    event.stopPropagation()
```
[the remark this answers is not in the document]
Comment (evdhoudt) [reply client/src/components/AdvancedSearch.js]: Events need to propagate further to get correct popover hide behavior

File: client/src/components/SearchBar.js [hunk 6]
```diff
@@ -18,27 +61,34 @@ const SearchBar = props => {
...
     }
   }, [query, setSearchTerms, queryTextUnchanged])
 
-  const [showAdvancedSearch, setShowAdvancedSearch] = useState(false)
   const placeholder = query.objectType
     ? "Filter " + SEARCH_OBJECT_LABELS[query.objectType]
     : "Search for " +
       searchObjectTypes.map(type => SEARCH_OBJECT_LABELS[type]).join(", ")
 
+  const PopoverContent = (
```
[the remark this answers is not in the document]
Comment (evdhoudt) [reply client/src/components/SearchBar.js]: > A few remarks about the responsiveness of the new Popover of the advanced select:
> 
>     * when a popover contains different filters (like the report attendees, see left navigation in the popover), the size of the popover changes depending on the selected filter, which gives strange effects
> 
>     * the popover doesn't resize enough when resizing the window (example: the report attendees widget), this used to be the case
> 
>     * the input fields of the advanced select widget are now quite small, the placeholder doesn't even always fit

We should fix these issues in a separate issue. The size of the popover depends on what is provided. So the actual table that is rendered inside the popover should be responsible for the size.

**Comment by evdhoudt** [comment]
While fixing the issues I've run into a proptype error in FormControl. "inputRef" expects a function instead of the provided object. I'm guessing this is because bootstrap is outdated and not fixed with the latest recommendations for using input refs. Not sure how to fix the prop-type issue and since everything is still working, i'm not sure if it is necessary.

File: client/src/components/AdvancedSearch.js [hunk 7]
```diff
@@ -53,18 +59,36 @@ const AdvancedSearch = props => {
...
     existingKeys.length < Object.keys(filterDefs).length
+
+  const advancedSearchMenuContent = (
+    <Menu
+      className={Classes.POPOVER_DISMISS}
+      style={{ maxHeight: "400px", overflowY: "auto" }}
+    >
+      {Object.keys(filterDefs).map(filterKey => (
+        <MenuItem
+          disabled={existingKeys.indexOf(filterKey) > -1}
```
Comment (gjvoosten) [inline client/src/components/AdvancedSearch.js]: Use `includes()` instead of `indexOf()`.

File: client/src/components/SearchBar.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (gjvoosten) [reply client/src/components/SearchBar.js]: Style-wise, only when something is a Component (or a constant) its name should start with a capital. `PopoverContent` is used as a prop variable, so its name should start with a lowercase letter.

File: client/src/pages/tasks/Form.js [hunk 8]
```diff
@@ -64,13 +64,13 @@ const BaseTaskForm = props => {
...
   const LongNameField = DictionaryField(Field)
-  const TaskCustomFieldRef1 = DictionaryField(AdvancedSingleSelect)
+  const TaskCustomFieldRef1 = DictionaryField(Field)
   const TaskCustomField = DictionaryField(Field)
   const PlannedCompletionField = DictionaryField(Field)
   const ProjectedCompletionField = DictionaryField(Field)
   const TaskCustomFieldEnum1 = DictionaryField(Field)
   const TaskCustomFieldEnum2 = DictionaryField(Field)
-  const ResponsiblePositonsMultiSelect = DictionaryField(AdvancedMultiSelect)
+  const ResponsiblePositonsMultiSelect = DictionaryField(Field)
```
Comment (gjvoosten) [inline client/src/pages/tasks/Form.js]: Fix typo in the name: `ResponsiblePositionsMultiSelect`.

File: client/src/pages/tasks/Form.js [hunk 9]
```diff
@@ -172,65 +172,78 @@ const BaseTaskForm = props => {
...
+                      objectType={Organization}
+                      fields={Organization.autocompleteQuery}
+                      queryParams={orgSearchQuery}
+                      valueKey="shortName"
+                      addon={ORGANIZATIONS_ICON}
+                    />
+                  }
                 />
 
                 <ResponsiblePositonsMultiSelect
```
Comment (gjvoosten) [inline client/src/pages/tasks/Form.js]: Typo in name.

File: client/tests/e2e/report.js [hunk 10]
```diff
@@ -49,8 +52,9 @@ test("Draft and submit a report", async t => {
     "topferness, christopf"
   )
 
-  let $attendeesShortcutTitle = await $("#attendees-shortcut-title")
-  await $attendeesShortcutTitle.click()
+  // click outside the overlay to make sure the $attendeesShortcutList closes
+  let $attendeesShortcutList = await $("#tasks-shortcut-list")
```
Comment (gjvoosten) [inline client/tests/e2e/report.js]: Variable name does not correspond with selected element.

File: client/src/HOC/LoaderHOC.js [hunk 11]
```diff
@@ -11,7 +11,10 @@ export const mapDispatchToProps = (dispatch, ownProps) => ({
 const LoaderHOC = isLoading => dataPropName => WrappedComponent => {
   return class LoaderHOC extends Component {
     static propTypes = {
-      loaderMessage: PropTypes.string
+      loaderMessage: PropTypes.oneOfType([
+        PropTypes.string,
+        PropTypes.object
+      ])
```
Comment (gjvoosten) [inline client/src/HOC/LoaderHOC.js]: `yarn run lint-fix` wraps this differently/

File: client/src/components/advancedSelectWidget/AdvancedSelect.js [hunk 12]
```diff
@@ -163,180 +145,146 @@ export default class AdvancedSelect extends Component {
...
+    if (this.state.showOverlay) {
+      return // Overlay is already open and we do not need to fetch data
     }
+    this.setState(
+      {
+        searchTerms: "",
+        isLoading: true
+      },
+      this.fetchResults()
+    )
```
Comment (gjvoosten) [inline client/src/components/advancedSelectWidget/AdvancedSelect.js]: This changes the behaviour: when clicking the icon (input field addon), which sets focus, the advanced select pop-up is no longer shown, only the input field gets focus.

**Comment by evdhoudt** [comment]
>     * strange effects

Discussed with Vassil about UI of the widget on Slack:
**Vassil Iordanov 4:47 PM**
Mara was taking a different approach - making the widget bigger - scaling it up to the whole search bar. I assume you two discussed that?
I like both, just curious how the reasoning went - was it for pragmatic reasons or design?
**Edwin van den Houdt 4:49 PM**
For now my reasoning was pragmatic to fix the issue at hand. And I saw another issue that was aimed towards fixing the responsiveness. I thought that would be a good ticket to then focus on the design for large and small screens

**Comment by evdhoudt** [comment]
> A few remarks about the responsiveness of the new Popover of the advanced select:
> 
>     * when a popover contains different filters (like the report attendees, see left navigation in the popover), the size of the popover changes depending on the selected filter, which gives strange effects
> 
>     * the popover doesn't resize enough when resizing the window (example: the report attendees widget), this used to be the case
> 
>     * the input fields of the advanced select widget are now quite small, the placeholder doesn't even always fit

Discussed with Vassil about UI of the widget on Slack:
Vassil Iordanov 4:47 PM
Mara was taking a different approach - making the widget bigger - scaling it up to the whole search bar. I assume you two discussed that?
I like both, just curious how the reasoning went - was it for pragmatic reasons or design?
Edwin van den Houdt 4:49 PM
For now my reasoning was pragmatic to fix the issue at hand. And I saw another issue that was aimed towards fixing the responsiveness. I thought that would be a good ticket to then focus on the design for large and small screens
