### PR TITLE
Change engagementDate format in emailed reports

### LINKED ISSUE #3361: Engagement date in e-mail report in wrong time-zone
**Describe the bug**
The time reported in the engagement report email is different then the time displayed in ANET.
I suspect ANET is showing the local time, and the [UTC / Zulu](https://en.wikipedia.org/wiki/Coordinated_Universal_Time) time communicated via e-mail.

**To Reproduce**
1. Ensure local time != [UTC](https://en.wikipedia.org/wiki/Coordinated_Universal_Time)
2. Trigger an engagement report
3. Compare time communicated via engagement report with ANET time

**Expected behavior**
The engagement date is consistent with the time displayed in ANET. I believe this should be the local timezone.

**Additional context**
The local time zone is different then [UTC](https://en.wikipedia.org/wiki/Coordinated_Universal_Time).

**Additional note**
It may be good to annotate times with the corresponding timezone. Although these reports are likely to be used withing the same region, it is still possible to forward these e-mails to users in different time-zones. Yet this annotation has no priority. 

Related to #3335: _Duration missing from report_

Fixing #3360 has a higher priority.

### PR DESCRIPTION
**Pull request by cemalettin-simsoft**
Change it to server's local time zone. Users will see the engagement date with the server time zone. `anet-dictionary` is also changed for email date formatter strings

Closes #3361 

#### User changes
- Users will see different server's local time zone engagement date in their report emails.

#### Super User changes
-

#### Admin changes
- `anet-dictionary.yml` is changed, `dateFormats.email` now have timezone part as well

#### System admin changes
- [x] anet.yml or anet-dictionary.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [X] Described the user behavior in PR body
  - [X] Referenced/updated all related issues
  - [X] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [X] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [ ] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [X] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

### CODE REVIEW

File: src/main/java/mil/dds/anet/threads/AnetEmailWorker.java [hunk 1]
```diff
@@ -131,19 +132,19 @@ protected void runInternal(Instant now, JobHistory jobHistory, Map<String, Objec
     emailContext.put("SUPPORT_EMAIL_ADDR", config.getDictionaryEntry("SUPPORT_EMAIL_ADDR"));
     emailContext.put("dateFormatter",
         DateTimeFormatter.ofPattern((String) config.getDictionaryEntry("dateFormats.email.date"))
-            .withZone(DaoUtils.getDefaultZoneId()));
```
Comment (VassilIordanov) [inline src/main/java/mil/dds/anet/threads/AnetEmailWorker.java:134]: `import mil.dds.anet.utils.DaoUtils;` is unused

Comment (VassilIordanov) [inline src/main/java/mil/dds/anet/threads/AnetEmailWorker.java:134]: Through the code, we now use both:
`ZoneId.systemDefault()`
and
`DaoUtils.getDefaultZoneId()`
As a result, it is not clear what the intent is and what is used when.
I propose to have 2 methods in DaoUtils:
`DaoUtils.getServerLocalZoneId()` -> delegates to ZoneId.systemDefault() and is used to format user-facing content such as emails
`DaoUtils.getServerNativeZoneId()` -> same behavior, and instead of, the currentl `DaoUtils.getDefaultZoneId()` and is used to define the native date representation for the database.

File: src/main/java/mil/dds/anet/threads/AnetEmailWorker.java [hunk 2]
```diff
@@ -131,19 +132,19 @@ protected void runInternal(Instant now, JobHistory jobHistory, Map<String, Objec
...
+            .withZone(ZoneId.systemDefault()));
```
Comment (VassilIordanov) [inline src/main/java/mil/dds/anet/threads/AnetEmailWorker.java:135]: the issue requests `It may be good to annotate times with the corresponding timezone.`. This can be done by changing the date string in `anet-dictionary.yml`. It would be good if this PR amends the example `anet-dictionary.yml` to do so.

**Review by VassilIordanov — CHANGES_REQUESTED** [review]

File: src/main/java/mil/dds/anet/utils/DaoUtils.java [hunk 3]
```diff
@@ -114,10 +114,14 @@ public static Person getUserFromContext(Map<String, Object> context) {
...
     return ZoneId.of("UTC");
   }
 
+  public static ZoneId getServerLocalZoneId() {
+    return ZoneId.systemDefault();
+  }
+
   public static ZoneOffset getDefaultZoneOffset() {
     return ZoneOffset.UTC;
   }
```
Comment (gjvoosten) [inline src/main/java/mil/dds/anet/utils/DaoUtils.java:127]: Should also rename this one to `getServerNativeZoneOffset()`.

**Review by gjvoosten — CHANGES_REQUESTED** [review]

**Review by gjvoosten — APPROVED** [review]

**Review by VassilIordanov — APPROVED** [review]
