### PR TITLE
Fix formCustomFields error when creating objects

### LINKED ISSUE #3508: Error about formCustomFields when creating location approval steps
**Describe the bug**
When creating location approval steps, ANET shows an error about `formCustomFields`.
The same may happen with the approval steps for tasks and organizations, so these need to be checked as well.

**To Reproduce**
Create a location and add some approval steps.

**Expected behavior**
Even though the approval process for locations is not yet used, it should work (obviously).

### PR DESCRIPTION
**Pull request by anilsonmez-simsoft**
Remove formCustomFields from position objects before sending them to the server to prevent errors.

Closes #3508 

#### User changes
- None

#### Super User changes
- Super Users can create locations, tasks, or organizations with engagement planning approval process and report publication approval process.

#### Admin changes
- Admins can create locations, tasks, or organizations with engagement planning approval process and report publication approval process.

#### System admin changes
- [ ] anet.yml or anet-dictionary.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [x] Described the user behavior in PR body
  - [x] Referenced/updated all related issues
  - [x] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [x] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [ ] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [x] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

### CODE REVIEW

File: client/src/components/Model.js [hunk 1]
```diff
@@ -120,6 +120,7 @@ export const NOTE_TYPE = {
 }
 
 export const DEFAULT_CUSTOM_FIELDS_PARENT = "formCustomFields"
+export const NOTES_FIELD = "notes"
```
Comment (gjvoosten) [inline client/src/components/Model.js:123]: I'd move this line to below the next line (kepping the custom fields consts together).

File: client/src/components/Model.js [hunk 2]
```diff
@@ -689,4 +690,18 @@ export default class Model {
         (note.customFields = utils.parseJsonSafe(note.text))
     )
   }
+
+  static COMMON_CLIENT_SIDE_FIELDS = [
```
Comment (gjvoosten) [inline client/src/components/Model.js:694]: I'd name this e.g. `FILTERED_CLIENT_SIDE_FIELDS`.

File: client/src/models/Location.js [hunk 3]
```diff
@@ -177,4 +178,20 @@ export default class Location extends Model {
     }
     return this.name
   }
+
+  static LOCATION_CLIENT_SIDE_FIELDS = [
```
Comment (gjvoosten) [inline client/src/models/Location.js:182]: I'd name this `FILTERED_CLIENT_SIDE_FIELDS` and define it as:
```
  static FILTERED_CLIENT_SIDE_FIELDS = [
    "displayedCoordinate",
    // TODO: do we need other fields here? e.g. I see "customFields" in some places
    ...Model.FILTERED_CLIENT_SIDE_FIELDS
  ]
```

File: client/src/models/Position.js [hunk 4]
```diff
@@ -199,4 +199,24 @@ export default class Position extends Model {
       return POSITIONS_ICON
     }
   }
+
+  static POSITION_CLIENT_SIDE_FIELDS = [
```
Comment (gjvoosten) [inline client/src/models/Position.js:203]: I'd name this `FILTERED_CLIENT_SIDE_FIELDS` and define it as:
```
  static FILTERED_CLIENT_SIDE_FIELDS = [
    // TODO: do we need other fields here? I see "previousPeople" in some places, and e.g. "customFields" and "responsibleTasks" elsewhere
    ...Model.FILTERED_CLIENT_SIDE_FIELDS
  ]
```

File: client/src/models/Location.js [hunk 5]
```diff
@@ -177,4 +178,20 @@ export default class Location extends Model {
...
+    "displayedCoordinate",
+    DEFAULT_CUSTOM_FIELDS_PARENT
+  ]
+
+  static getObjClientSideFieldsFiltered(obj) {
```
Comment (gjvoosten) [inline client/src/models/Location.js:187]: Perhaps this needs an optional second argument (or a variable argument list) for fields that you may want to remove incidentally (i.e. only in some places, not everywhere). Could then also become a generic function in `Model.js`, to be used by all models.

File: client/src/models/Location.js [hunk 6]
```diff
@@ -177,4 +178,20 @@ export default class Location extends Model {
...
+    // filter commons first
+    const newObj = Model.getObjClientSideFieldsFiltered(obj)
+    // Also filter for position specific if there is any
+    return Object.without(newObj, ...Location.LOCATION_CLIENT_SIDE_FIELDS)
+  }
+
+  getObjClientSideFieldsFiltered() {
```
Comment (gjvoosten) [inline client/src/models/Location.js:194]: This would then also need that optional argument (list).

**Review by gjvoosten — CHANGES_REQUESTED** [review]

File: client/src/components/Model.js [hunk 7]
```diff
@@ -689,4 +690,21 @@ export default class Model {
         (note.customFields = utils.parseJsonSafe(note.text))
     )
   }
+
+  static FILTERED_CLIENT_SIDE_FIELDS = [
+    NOTES_FIELD,
+    DEFAULT_CUSTOM_FIELDS_PARENT /* , others */
+  ]
+
+  static getObjClientSideFieldsFiltered(obj, ...additionalFields) {
```
Comment (gjvoosten) [inline client/src/components/Model.js:699]: Proposed change: name these methods `filterClientSideFields`

File: client/src/models/Position.js [hunk 8]
```diff
@@ -199,4 +199,27 @@ export default class Position extends Model {
       return POSITIONS_ICON
     }
   }
+
+  static FILTERED_CLIENT_SIDE_FIELDS = [
+    /* fill if necessary */
```
Comment (gjvoosten) [inline client/src/models/Position.js:204]: Single-line comments are fine as `// fill if necessary`

**Review by gjvoosten — APPROVED** [review]
