### PR TITLE
Fix invalid dom warnings in compact view of reports

### LINKED ISSUE #3701: Invalid DOM in compact view of reports
**Describe the bug**
Invalid DOM in compact view of reports.
[Note: error does not happen on compact view of people.]

**To Reproduce**
1. Go to a report on localhost:3000
2. Click on 'Summary/Print'
3. See errors in developer console like:
```
Warning: validateDOMNesting(...): <tr> cannot appear as a child of <td>.
    in tr (created by Styled(tr))
    in Styled(tr) (at Compact.js:284)
    in CompactTitle (at Compact.js:277)
    in td (at Compact.js:187)
    in tr (at Compact.js:186)
    in tbody (at Compact.js:185)
    in table (created by Styled(table))
    in Styled(table) (at Compact.js:178)
    in CompactTable (at Compact.js:276)
    in div (created by Styled(div))
    in Styled(div) (at Compact.js:274)
    in Formik (at Compact.js:261)
    in CompactReportView (created by Connect(CompactReportView))
    in Connect(CompactReportView) (created by Context.Consumer)
    in Route (at Routing.js:62)
    in Switch (at Routing.js:59)
    in Route (at Routing.js:56)
    in Switch (at Routing.js:51)
    in Routing (at App.js:203)
    in div (created by ElementWrapper)
    in ElementWrapper (created by Element)
    in Element (at ResponsiveLayout.js:102)
    in div (at ResponsiveLayout.js:84)
    in div (at ResponsiveLayout.js:76)
    in ResponsiveLayout (at App.js:192)
    in App (created by Connect(App))
    in Connect(App) (created by Context.Consumer)
    in Route (at src/index.js:29)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:28)
    in ApolloProvider (at src/index.js:27)
    in PersistGate (at src/index.js:26)
    in Provider (at src/index.js:25)
```

**Environment (please complete the following information):**
 - Happens under both Chrome and Firefox

### PR DESCRIPTION
**Pull request by anilsonmez-simsoft**
Added page size selection to report print view.
Fixed invalid dom warnings in compact view of reports.

Closes #3701 

#### User changes
- Users can now select a page size for printing reports.

#### Super User changes
- none

#### Admin changes
- none

#### System admin changes
- [ ] anet.yml or anet-dictionary.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [x] Described the user behavior in PR body
  - [x] Referenced/updated all related issues
  - [x] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [x] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [ ] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [ ] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

### CODE REVIEW

File: client/src/components/Compact.js [hunk 1]
```diff
@@ -234,8 +251,8 @@ export const CompactRow = ({ label, content, ...otherProps }) => {
 
   return (
     <CustomStyled className={className || null}>
-      <RowLabelS isTopLevelTh={isTopLevelTh}>{label}</RowLabelS>
-      <CompactRowContentS>{content}</CompactRowContentS>
+      {label && <RowLabelS isTopLevelTh={isTopLevelTh}>{label}</RowLabelS>}
```
Comment (gjvoosten) [inline client/src/components/Compact.js:254]: Perhaps rename `isTopLevelTh` to something like `isHeaderRow`?

**Review by gjvoosten — CHANGES_REQUESTED** [review]

**Review by gjvoosten — APPROVED** [review]
