### PR TITLE
Parallellise client side tests

### LINKED ISSUE #212: Parallellise client-side tests
The client tests are run with `ava … --serial --fail-fast`. If we could run them in parallel it would seriously speed up things. Unfortunately there are dependencies between tests, so when running then just as `ava …` without the other options, some tests fail intermittently. Look into either making tests independent or figuring out a way to explicitly specify test order/dependencies where necessary (e.g. all the 404 tests can easily run in parallel).

### PR DESCRIPTION
**Pull request by oayvazoglusim**
This PR contains the following changes : 

Client-side e2e tests are parallellised when executed locally by removing --serial from ava flags.
Except that report.js tests are explicitly configured ( by using test.serial() ) to run serially because there are three tests in report.js and all use some shared state. 
Since we have 1 parallel test on our browserstack plan, ava configuration extracted to its own file in order to differentiate between local and remote testing

### Release notes

Closes #212 

#### User changes
-

#### Super User changes
-

#### Admin changes
-

#### System admin changes

- [ ] anet.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [ ] Described the user behavior in PR body
  - [ ] Referenced/updated all related issues
  - [x] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [x] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [x] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [ ] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

### CODE REVIEW

File: client/tests/util/test.js [hunk 1]
```diff
@@ -50,6 +50,28 @@ test.beforeEach(t => {
...
+       * which is a singleton, shared amongst different driver instances. As a result same
+       * ChromeDriver server process is used by different drivers. When driver.quit() is called by
+       * one of divers that process is terminated. By explicitly defining a new ServiceBuilder
+       * here we enforce creation of seperate ChromeDriver server child processes for each driver instance
+       *
+       * if it is not feasible to create seperate ChromeDriver server child processes for each driver;
+       * instead of driver.quit(), driver.close() can be used in afterEach.always hook and
+       * driver.quit() can be called on after.always hook
+       */
+      .setChromeService(new chrome.ServiceBuilder())
```
Comment (gjvoosten) [inline client/tests/util/test.js:74]: So why not remove this entirely, and make this change instead:
```
diff --git a/client/tests/util/test.js b/client/tests/util/test.js
index a155748b2..63d8f028b 100644
--- a/client/tests/util/test.js
+++ b/client/tests/util/test.js
@@ -380,8 +358,16 @@ test.beforeEach(t => {
   }
 })
 
-// Shut down the browser when we are done.
+// Close the driver
 test.afterEach.always(async t => {
+  if (t.context.driver) {
+    await t.context.driver.close()
+  }
+})
+
+// The driver is shared among the parallel sessions,
+// so only shut down the browser when we are done with all tests.
+test.after.always(async t => {
   if (t.context.driver) {
     await t.context.driver.quit()
   }
```
?

File: client/tests/util/test.js [hunk 2]
```diff
@@ -50,6 +50,28 @@ test.beforeEach(t => {
...
+       * which is a singleton, shared amongst different driver instances. As a result same
+       * ChromeDriver server process is used by different drivers. When driver.quit() is called by
+       * one of divers that process is terminated. By explicitly defining a new ServiceBuilder
+       * here we enforce creation of seperate ChromeDriver server child processes for each driver instance.
+       *
+       * If it is not feasible to create seperate ChromeDriver server child processes for each driver;
+       * instead of driver.quit(), driver.close() can be used in afterEach.always hook and
+       * driver.quit() can be called on after.always hook.
+       */
+      .setChromeService(new chrome.ServiceBuilder())
```
Comment (gjvoosten) [inline client/tests/util/test.js:74]: Again, why not remove this entirely, and make this change instead:
```
diff --git a/client/tests/util/test.js b/client/tests/util/test.js
index 0361b93b9..37d819562 100644
--- a/client/tests/util/test.js
+++ b/client/tests/util/test.js
@@ -380,8 +380,16 @@ test.beforeEach(t => {
   }
 })
 
-// Shut down the browser when we are done.
+// Close the driver
 test.afterEach.always(async t => {
+  if (t.context.driver) {
+    await t.context.driver.close()
+  }
+})
+
+// The driver is shared among the parallel sessions,
+// so only shut down the browser when we are done with all tests.
+test.after.always(async t => {
   if (t.context.driver) {
     await t.context.driver.quit()
   }```
?

Comment (ysf-simsoft) [reply client/tests/util/test.js:74]: Honestly, I haven't tested the change you propose. I have done all of my tests with current change and it works just fine. Also I choose first approach, because it is less code. I can't see any practical difference between two of them. But if you insist on the second approach, it is fine to me. I can test and make the change.

Comment (gjvoosten) [reply client/tests/util/test.js:74]: In that case, at least rewrite/condense the extensive comment to just the factual reason for using a separate service on each driver.

File: client/tests/util/test.js [hunk 3]
```diff
@@ -51,25 +51,12 @@ test.beforeEach(t => {
...
-       * Without this line, even though all assertions pass, afterEach.always hook report intermittent errors.
-       * Usually first one or two tests execute successfully where rest of the tests raise errors.
-       * These erros are "ECONNREFUSED connect ECONNREFUSED 127.0.0.1:XXXXX" which are coming from webdriver.
-       * beforeEach hook creates a new driver for every test and they are
-       * supposed to run in isolation without affecting each other. At this point my best guess is that
-       * when driver.quit() is called, webdriver shuts down ChromeDriver server process thus causing
-       * subsequent requests to ChromeDriver server process fails.
-       *
-       * Further investigation of the issue lead me to following consequences;
        * If we don't explicitly define ServiceBuilder for ChromeDriver it uses default ServiceBuilder
```
Comment (gjvoosten) [inline client/tests/util/test.js:54]: "… uses **a** default …"

File: client/tests/util/test.js [hunk 4]
```diff
@@ -51,25 +51,12 @@ test.beforeEach(t => {
...
        * which is a singleton, shared amongst different driver instances. As a result same
```
Comment (gjvoosten) [inline client/tests/util/test.js:55]: "… result, **the** same …"

File: client/tests/util/test.js [hunk 5]
```diff
@@ -51,25 +51,12 @@ test.beforeEach(t => {
...
        * ChromeDriver server process is used by different drivers. When driver.quit() is called by
-       * one of divers that process is terminated. By explicitly defining a new ServiceBuilder
+       * one of drivers that process is terminated. As a result even though all assertions pass,
```
Comment (gjvoosten) [inline client/tests/util/test.js:57]: "… one of **the** drivers …"

File: client/tests/util/test.js [hunk 6]
```diff
@@ -51,25 +51,12 @@ test.beforeEach(t => {
...
+       * afterEach.always hook report intermittent errors. By explicitly defining a new ServiceBuilder
```
Comment (gjvoosten) [inline client/tests/util/test.js:58]: "… **the** afterEach.always hook **reports** …"

File: client/tests/util/test.js [hunk 7]
```diff
@@ -51,25 +51,12 @@ test.beforeEach(t => {
...
        * here we enforce creation of seperate ChromeDriver server child processes for each driver instance.
```
Comment (gjvoosten) [inline client/tests/util/test.js:59]: "… enforce **the** creation of **a** **separate** …"

File: client/ava.config.js [hunk 8]
```diff
@@ -0,0 +1,48 @@
...
+
+const config = {
+  files: ["tests/e2e/*.js"],
+  failFast: true,
+  verbose: true,
+  timeout: "3m",
+  serial: true
+}
+
+const testEnv = (process.env.GIT_TAG_NAME && "remote") || process.env.TEST_ENV || "local"
```
Comment (gjvoosten) [inline client/ava.config.js:15]: Please run `yarn run lint-fix`.

File: client/tests/util/test.js [hunk 9]
```diff
@@ -50,6 +50,15 @@ test.beforeEach(t => {
     builder = builder
       .forBrowser("chrome")
       .setChromeOptions(new chrome.Options().headless())
+      /*
+       * If we don't explicitly define ServiceBuilder for ChromeDriver it uses a default ServiceBuilder
+       * which is a singleton, shared amongst different driver instances. As a result, the same
+       * ChromeDriver server process is used by different drivers. When driver.quit() is called by
+       * one of the drivers, that process is terminated. As a result even though all assertions pass,
+       * the afterEach.always hook reports intermittent errors. By explicitly defining a new ServiceBuilder
+       * here we enforce the creation of a seperate ChromeDriver server child process for each driver instance.
```
Comment (gjvoosten) [inline client/tests/util/test.js:59]: *seperate* → *separate*
