### PR TITLE
Fix text in editor being duplicated

### LINKED ISSUE #1950: Text duplicated in the Engagement Details, Sensitive Information and Biography data fields
If any text is entered in these three fields, the text is duplicated when the focus leaves the respective data field.

For example:
1. Create a new report
2. Type or copy text into the "Engagement details" data field
3. Click anywhere else on the report with the mouse

Result: the text entered into the "Engagement details" data field is duplicated in the data field.

However, after clicking the "Preview and submit" button, the duplicated text is no longer displayed.  When editing the report after the initial "Preview and submit," the duplicated text is also no longer displayed.

### PR DESCRIPTION
**Pull request by maradragan**
Fixes #1950

### User changes
This makes sure that when creating a new report and filling in one of
the following fields: Engagement Details, Sensitive Information and
Biography, the text is no longer being duplicated the first time we
click outside the field.

### CODE REVIEW

File: client/src/components/RichTextEditor.js [hunk 1]
```diff
@@ -118,16 +101,22 @@ class RichTextEditor extends Component {
...
+        blocksFromHTML.contentBlocks,
+        blocksFromHTML.entityMap
+      )
     }
-    const contentState = ContentState.createFromBlockArray(
-      blocksFromHTML.contentBlocks,
-      blocksFromHTML.entityMap
-    )
-    this.pushEditorState(contentState)
+    return ""
```
Comment (gjvoosten) [inline client/src/components/RichTextEditor.js]: Could this be just `return` like line 108 above?
