### PR TITLE
Fix rich text fields displaying html tags

### LINKED ISSUE #3859: Rich text fields display html tags
**Describe the bug**
Rich text field assessments display HTML tags on the sidebar notes and instant assessment results.

**Expected behavior**
Rich text values should be displayed with the correct styling.

### PR DESCRIPTION
**Pull request by anilsonmez-simsoft**
Rich text assessments are displayed with correct styling on `relatedObjectNotes` and instant assessment results.

Closes #3859 

#### User changes
- Users can display rich text assessment results with correct styling

#### Super User changes
- None

#### Admin changes
- None

#### System admin changes
- [ ] anet.yml or anet-dictionary.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [x] Described the user behavior in PR body
  - [x] Referenced/updated all related issues
  - [x] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [x] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [ ] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [ ] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

### CODE REVIEW

File: client/src/components/RelatedObjectNotes.js [hunk 1]
```diff
@@ -276,11 +276,24 @@ const RelatedObjectNotes = ({
                           .filter(
                             field => !EXCLUDED_ASSESSMENT_FIELDS.includes(field)
                           )
-                          .map(field => (
-                            <p key={field}>
-                              <i>{field}</i>: <b>{jsonFields[field]}</b>
-                            </p>
-                          ))}
+                          .map(field => {
+                            const isRichTextField = utils.isValidHtmlWithTags(
```
Comment (gjvoosten) [inline client/src/components/RelatedObjectNotes.js:280]: In principle this should only be true if the dictionary defines the field as having a `richTextEditor` widget.

File: client/src/components/RelatedObjectNotes.js [hunk 2]
```diff
@@ -276,11 +276,24 @@ const RelatedObjectNotes = ({
...
+                              jsonFields[field]
+                            )
+                            const fieldValue = isRichTextField
+                              ? parseHtmlWithLinkTo(jsonFields[field])
+                              : jsonFields[field]
```
Comment (gjvoosten) [inline client/src/components/RelatedObjectNotes.js:285]: What if the field contains an array (where each item in the array could have a rich-text element)?

**Review by gjvoosten — CHANGES_REQUESTED** [review]

File: client/src/components/RelatedObjectNotes.js [hunk 3]
```diff
@@ -171,7 +176,7 @@ const RelatedObjectNotes = ({
             const jsonFields =
               isJson && note.text ? utils.parseJsonSafe(note.text) : {}
             const noteText = isJson
-              ? jsonFields.text
+              ? parseHtmlWithLinkTo(jsonFields.text)
               : parseHtmlWithLinkTo(note.text)
```
Comment (gjvoosten) [inline client/src/components/RelatedObjectNotes.js:180]: Suggested change: `const noteText = parseHtmlWithLinkTo(isJson ? jsonFields.text : note.text)`

**Review by gjvoosten — CHANGES_REQUESTED** [review]

File: client/src/components/aggregations/RichTextWidget.js [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+  }
+  return (
+    <div>
+      <Button
+        className="toggle-section-button"
+        style={{ marginBottom: "1rem" }}
+        onClick={() => setShowValues(!showValues)}
+        id="toggleShowValues"
+      >
+        {showValues ? "Hide" : "Show"} {filteredValues.length} values
```
Comment (gjvoosten) [inline client/src/components/aggregations/RichTextWidget.js:24]: Displays: "Show 1 values" (or 'Hide') when there's only one value. Suggestion to make a util method that uses `import pluralize from "pluralize"` and pluralizes "value" based on length, and use that here and in `client/src/components/aggregations/DefaultAggWidget.js`.

**Review by gjvoosten — CHANGES_REQUESTED** [review]

**Review by gjvoosten — APPROVED** [review]
